let aarogyasri = [
    "Superficial Parotoidectomy(Non-malignant)",
    "Laproscopic Hemi Thyroidectomy",
    "Laproscopic Isthmectomy",
    "Laproscopic Sub total Thyroidectomy",
    "Laproscopic Total Thyroidectomy",
    "Laproscopic Surgical treatment for Epigastric Hernia repair with Mesh",
    "Laproscopic Surgical treatment for Unilateral Femoral Hernia With Mesh",
    "Laproscopic Surgical treatment for Hiatus Hernia With Mesh",
    "Laproscopic Surgical treatment for - Umbilical Hernia With Mesh",
    "Herinoplasty with Mesh Direct Inguinal Hernia",
    "Laproscopic Surgical treatment for Incisional Hernia with Mesh",
    "Laproscopic Surgical treatment for Duodenal Perforation",
    "Excision of Meckel's Diverticulum",
    "Laproscopic Colectomy (Total Colectomy)",
    "Rectovaginal fistula Management without Colostomy",
    "Loop Colostomy Sigmoid",
    "Rectopexy Open with Mesh for Rectal Prolapse",
    "Laproscopic Rectopexy With Mesh for Rectal Prolapse",
    "Laproscopic Cholecystectomy With CBD Exploration",
    "Excision and Ligation of Varicose Veins",
    "Myringoplasty",
    "Myringoplasty with ossiculoplasty",
    "Myringotomy with grommet for one ear",
    "Septo rhinoplasty",
    "Exenteration of Orbit",
    "Glaucoma Surgery",
    "Joint reconstruction/intraarticular fractures",
    "Arthrodesis of foot Small joints",
    "Bone tumor surgery reconstruction with internal fixation",
    "Anal Sphincter Repair -With Colostomy",
    "Rectovaginal fistula Management with Colostomy",
    "Coronary Balloon Angioplasty with Drug eluting sten",
    "PTCA 1 Additional Drug eluting Stent",
    "Surgical management of Empyema Thoracis",
    "Meningo Myelocele Spinal Procedure",
    "Empyema decortication In Paediatric Patients",
    "Meckel's Diverticulectomy In Paediatric Patients",
    "Unilateral Inguinal Hernia repair In Paediatric Patients",
    "Bilateral Inguinal Hernia repair In Paediatric Patients",
    "Lumbar Hernia repair In Paediatric Patients",
    "Femoral Hernia repair In Paediatric Patients",
    "Umbilical Hernia repair In Paediatric Patients",
    "Incisional Hernia repair In Paediatric Patients",
    "Balloon dialatation of transplant Renal Artery stenosis ",
    "Excision of Ureterocele with Ureteric Implantation",
    "Balloon dilatation of Ureteric stricture",
    "Open radical Prostratectomy",
    "Partial Cystectomy",
    "Bladder neck reconstruction for Incontinence",
    "Mid urethral sling procedure for stress urinary incontinence",
    "CAPD-Tenchkoff catheter insertion",
    "CAPD-Tenchkoff catheter removal",
    "CAPD bags per month",
    "Cranioplasty With Impants",
    "Laminoplasty With Implants",
    "Chemotherapy for Breast Cancer with Docetaxel",
    "Chemotherapy for Non SMAL cell Lung Cancer with Erlotinib",
    "Chemotherapy for Non SMAL cell Lung Cancer with PEM + Cisplatin",
    "Chemotherapy for Non SMAL cell Lung Cancer with GEFITINIB",
    "Chemotherapy for Non SMAL cell Lung Cancer with Paclitaxel /Carboplatin",
    "Chemotherapy for Gastric Cancer with EOX",
    "Chemotherapy for Gastric Cancer with Gemcitabine+Oxaliplatin",
    "Chemotherapy for Gastric Cancer with Gemcitabine / Cisplatin",
    "Chemotherapy for Gastric Cancer with Imatinib(CML)",
    "Chemotherapy for Gastric Cancer with Dcf",
    "Chemotherapy for Colorectal Cancer with Capecitabine + bevacizumab (metastatic)",
    "Chemotherapy for Colorectal Cancer with Capecitabine + Oxalipantia (adjuvant) and metastatic",
    "Chemotherapy for Colorectal Cancer with Capacitabine",
    "Chemotherapy for Non Hodgkin Lymphoma with R - chop",
    "Chemotherapy Chemotherapy for Hepatoblastoma operable with Sorafenib",
    "Chemotherapy for Neuroblastoma (Stages I-III ) PCV (medulloblastoma)",
    "Chemotherapy for Multiple myeloma with Lenalidomide dexa",
    "Chemotherapy for Multiple myeloma with MPT(myeloma)",
    "Chemotherapy for Multiple myeloma with Imatinib (GSIT)",
    "Chemotherapy for Chronic lymphoid leukemia with Benadamustine",
    "Chemotherapy for Chronic lymphoid leukemia with Chilorambucil",
    "Chemotherapy for Chronic lymphoid leukemia with IA",
    "Chemotherapy for Chronic lymphoid leukemia with Imatinib(CML)",
    "Chemotherapy for Chronic lymphoid leukemia with Sunitinib",
    "Chemotherapy With Temozolamide (brain tumours)",
    "Chemotherapy With Benadamustin -RITUXIMAB",
    "Chemotherapy With TIP (GCT 2nd line)",
    "Chemotherapy with Capeiri (metastatic)",
    "Chemotherapy with Capeox (adjuvant) and metastatic",
    "Tarsorrhaphy surgery to prevent exposure keratitis to prevent loss or impairment of vision especially in facial burns",
    "Panfacial fractures combination with polytrauma",
    "Aplasia / hypoplasia / post traumatic loss of thumb for reconstruction - conventional surgery",
    "Reimplantation / revascularization - single digit",
    "Reimplantation / revascularization - multiple digits per finger",
    "Flap cover for trauma of the hand / forearm / arm / foot / leg / thigh etc., with exposure of the underlying vital structures like tendons, nerves, vessels, bone, with or without any fracture - flap insert",
    "Medical Management of Dengue Haemorrhagic Fever",
    "Medical Management of Rheumatic heart disease in Paediatric patient",
    "Medical Management of Auto immune hemolytic anemia in Paediatric patient",
    "Medical Management of Diphtheria in Paediatric patient",
    "Medical Management of Acute Glomerulo Nephritis",
    "Medical Management of Pneumonias",
    "Hypopiturasim Initial Evaluation And Management With Growth Hormone",
    "Hypopiturasim Maintanance Phase Monthly Package For Growth Hormone",
    "Medical Management of Grave'S Disease",
    "Medical Management of Cirrhosis Decompensated Including SBP, Portal HTN, Bleed",
    "Medical Management of Acute Hepatitis (Viral, Alcohol, Drugs, Misc. Infections)",
    "Medical Management of Ascities Of Any Etiology (Tubercolor, Melignant, Pancreatic, Biliary)"
]

aarogyasri = new Set(aarogyasri.map(elem => elem.toLowerCase()))
module.exports = aarogyasri